spring:
  shardingsphere:
    datasource:
      names: master,slave0
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://trivialfs.fofcn.com:3306/trivialfs_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&connectionTimeZone=GMT+8
        username: trivialfs_user
        password: Yy123456.
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 600000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        asyncInit: true
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://trivialfs.fofcn.com:3306/trivialfs_db0?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&connectionTimeZone=GMT+8
        username: trivialfs_user
        password: Yy123456.
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 600000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        asyncInit: true
    props:
      sql:
        show: true
    sharding:
      tables:
        trade_order:
          actual-data-nodes: ds0.trade_order_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: trade_order_$->{id % 2}
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-names: slave0

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.fofcn.trivialfs.web.entity
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

management:
  health:
    db:
      enabled: false